# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14nHkHf5PR8xeQuZVxAQymd7yR3-isKST
"""

cd

ls

